apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jenkins
  labels:
    app: nfs-jenkins
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: ""
  capacity:
    storage: 200Gi

  accessModes:
  - ReadWriteMany
  mountOptions: 
    - hard   
    - nfsvers=4.2
  nfs:
    path: "/jenkins"
    server: nfs-server.nfs.svc.cluster.local
    readOnly: false
  persistentVolumeReclaimPolicy: Retain



---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jenkins
  labels:
    app: nfs-jenkins
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  volumeName: pv-jenkins

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sshfarmanager
  labels:
    app: nfs-sshfarmanager
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: ""
  capacity:
    storage: 200Gi

  accessModes:
  - ReadWriteMany
  mountOptions: 
    - hard   
    - nfsvers=4.2
  nfs:
    path: "/sshFarmanager"
    server: nfs-server.nfs.svc.cluster.local
    readOnly: false
  persistentVolumeReclaimPolicy: Retain



---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sshfarmanager
  labels:
    app: nfs-sshfarmanager
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  volumeName: pv-sshfarmanager

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-farmanager-farmact
  labels:
    app: nfs-farmanager-farmact
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: ""
  capacity:
    storage: 200Gi

  accessModes:
  - ReadWriteMany
  mountOptions: 
    - hard   
    - nfsvers=4.2
  nfs:
    path: "/farmanager_farmact"
    server: nfs-server.nfs.svc.cluster.local
    readOnly: false
  persistentVolumeReclaimPolicy: Retain



---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-farmanager-farmact
  labels:
    app: nfs-farmanager-farmact
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  volumeName: pv-farmanager-farmact

